[repository]
# The name of the github owner, must be in lower-case letters
REGISTRY_NAME = "lidiriel"
# The name of this Pieces repository
REPOSITORY_NAME = "liphy_hw_domino_pieces"
# The label of this Pieces repository, as it will appear in Domino GUI
REPOSITORY_LABEL = "Liphy hardware pieces"
# The version of this Pieces release
VERSION = "0.1"

